### ISSUE TITLE
Not returning custom fields in version 6

### ISSUE THREAD

**Issue by arturludan** [pipedrive/client-php#100]
Сustom fields are not returned when I use the getDeals()/getDeal()/getPersons()/getPerson() methods.
During debugging, I see custom fields in the response, but after deserialization, they don't get into the object.
In version 4, the fields are present.

**Comment by mattbloomfield** [comment]
Same, this makes the sdk unusable for us!

**Comment by siirimangus** [comment]
Hey, thank you for noticing and reporting. It seems this sadly really is the case. But I'm closing this issue as it is a duplicate of that one and keep the conversation going on there: https://github.com/pipedrive/client-php/issues/105
