### ISSUE TITLE
MailThread does not hold additional data

### ISSUE THREAD

**Issue by aistis-** [pipedrive/client-php#12]
Hi! It seams `src/Models/MailThread.php` does not hold `additionalData` even API endpoint returns it. As a result pagination feature is missing from the endpoint when using the client.

See an example of existed pagination: https://github.com/pipedrive/client-php/blob/master/src/Models/GetDeals.php#L69

**Comment by DenisButCheR** [comment]
Hello @aistis- . Can you please provide more detailed information about your problem with some code examples and response messages? Thanks for your feedback!

**Comment by aistis-** [comment]
Hi. I no longer work on the topic. However, Even API response returns `additionalData` from API, it is not expose at `MailThread` model in `jsonSerialize()` function.

In my case, I override the entire `MailThread` class adding custom `jsonSerialize()` method.
