### ISSUE TITLE
AddFile return error

### ISSUE THREAD

**Issue by amelsf** [pipedrive/client-php#18]
Hi
I'm trying to add a document to pipdrive but I have the following error: operation aborted by callback and i don't undestrand the error

My code

```
  $pipeDrive = $this->client;
 $files = $pipDrive->getFiles();
$collect['file'] = $pathfile ;  // public/uploads/filename.pdf =>
$collect['personalId'] = 1;
$files->addFile($collect);
```
Thank's for help

**Comment by joffnerd** [comment]
I am also struggling with this.

Can you provide a code example of addFile where we start off with a path to a file and it is then multipart/form-data encoded please?
