### ISSUE TITLE
ItemSearch missing

### ISSUE THREAD

**Issue by zeman** [pipedrive/client-php#26]
This library looks out of date as it's using deprecated search functions like `findPersonsByName`. Will it be updated with the `ItemSearch` controller or should we move too interacting with the API directly?

**Comment by mykhailo-riabokon** [comment]
@zeman sorry for the long reply and thank you for reporting this issue. All missing search endpoints were added in 1.1.0

Deprecated methods should be removed in the next major version.

https://github.com/pipedrive/client-php/pull/32
