### ISSUE TITLE
Using deprecated methods

### ISSUE THREAD

**Issue by jeremyfrench** [pipedrive/client-php#31]
I've just started a project using this library, and in general, it's done a good job, however, it seems a little out of date
https://developers.pipedrive.com/docs/api/v1
```
 Published: 8 April 2020

On 31 March 2021 we will remove the following endpoints:
    GET /deals/find
    GET /organizations/find
    GET /persons/find
    GET /products/find
    GET /searchResults
    GET /searchResults/field
```

All of these endpoints are in the library, and more importantly perhaps, their replacements are not. Is there a plan to update this to support the new methods?

**Comment by jethromay** [comment]
Experiencing the same..

**Comment by mykhailo-riabokon** [comment]
@jeremyfrench thank you for reporting this issue. All missing search endpoints were added in 1.1.0

Deprecated methods should be removed in the next major version.

https://github.com/pipedrive/client-php/pull/32
