### ISSUE TITLE
APIHelper:appendUrlWithQueryParameters breaks things when there are no parameters

### ISSUE THREAD

**Issue by alex-bukach** [pipedrive/client-php#36]
I have faced an issue that I get 401 response when sending `PipelinesController::getOnePipeline` request with only pipeline ID as options. Then `APIHelper::appendUrlWithQueryParameters` just adds a question mark to the query which screws up the things.

**Comment by alex-bukach** [comment]
Fixed in https://github.com/pipedrive/client-php/pull/37

**Comment by alex-bukach** [comment]
@Rodz13 could you explain why the issue has been closed? The pull request is still open.

**Comment by Rodz13** [comment]
> @Rodz13 could you explain why the issue has been closed? The pull request is still open.

Hey there! According to the comment you left this issues is fixed in #37.

**Comment by alex-bukach** [comment]
@Rodz13 the issue has been fixed in https://github.com/pipedrive/client-php/pull/37, however https://github.com/pipedrive/client-php/pull/37 has not been merged to the main branch yet, so it makes sense to re-open this issue until the branch is merged.
