### ISSUE TITLE
Leads API

### ISSUE THREAD

**Issue by rostyslawbulych** [pipedrive/client-php#39]
Hi guys,

Any plans to implement methods for Leads management via API?

Thanks,
Ros

**Comment by Rodz13** [comment]
Hi Ros,

Thank you for your message and apologies for the delay. 

We do have the Leads in the swagger config - [Leads](https://developers.pipedrive.com/docs/api/v1/Leads#getLeads).

Also, we will be releasing a new version of client-php in the upcoming days.


Hope it helps.

Have a great day! 

Rod
