### ISSUE TITLE
Return types of API responses are void

### ISSUE THREAD

**Issue by alexandersch** [pipedrive/client-php#4]
A lot of times the return type of API calls are void when they are returning an array of data. Could you please update them to a correct value?

E.g.:
`@return void response from the API call`
To:
`@return mixed response from the API call` 
Or: 
`@return array response from the API call` 

Thanks in advance.

**Comment by Tlapi** [comment]
This really needs updating.

**Comment by mschop** [comment]
This issue is open now for about three months. When can we expect this to be fixed? This is really bad because all code quality tools warn about this.

I find it worth considering, that the official client seems to have a lower quality than the community library.

**Comment by DenisButCheR** [comment]
Hello @alexandersch . Thanks for your report. I can confirm that this is a problem and we will fix it in the future versions of the library. It is in our backlog.

**Comment by andrii-pukhalevych** [comment]
1 year to update doc block seems to be too much ;)

**Comment by karol-bialkowski** [comment]
+1 When this fix will be resolved? :)

**Comment by estevanjantsk** [comment]
Closing this issue since we fixed on https://github.com/pipedrive/client-php/issues/59
