### ISSUE TITLE
Call Logs Endpoint Missing

### ISSUE THREAD

**Issue by VijeshDatt** [pipedrive/client-php#43]
Hi guys, 

Just wanted to know if the Call Logs endpoint is somewhere in the documentation or has it been missed? 

https://developers.pipedrive.com/docs/api/v1/CallLogs

Hopefully this can be added soon.

**Comment by ziimk** [comment]
Hi! Call logs endpoints have been added: https://github.com/pipedrive/client-php/pull/46

**Comment by VijeshDatt** [comment]
Woohoo, thank you very much!
