### ISSUE TITLE
Optional fields must be handled properly

### ISSUE THREAD

**Issue by Meeshalk** [pipedrive/client-php#47]
Error:
array_values() expects parameter 1 to be array, null given

[Line Responsible](https://github.com/pipedrive/client-php/blob/28e562416f7bc3c29b0e107247c7f046ba7b50c8/src/Controllers/PersonsController.php#L449)

Method: Update A person

Input:
````
[
'id' => Int,
'custon_field_key' => Int
]

**Comment by ziimk** [comment]
@Meeshalk thank you for noticing! The [PR](https://github.com/pipedrive/client-php/pull/48) is open, would you be able to test it on your side as well to make sure it works as expected?

**Comment by Meeshalk** [comment]
@ziimk Thanks to you as well. I was going to submit a PR. Will test it tomorrow. 

Thanks again

**Comment by Meeshalk** [comment]
@ziimk Sorry for the delay. I have tested. #48 fixes this issue.
