### ISSUE TITLE
Wrong param docs for addADeal

### ISSUE THREAD

**Issue by Tlapi** [pipedrive/client-php#5]
In function docs there is: `@param object $body (optional) TODO: type description here` but there should be `array`.

**Comment by mykhailo-riabokon** [comment]
Hi @Tlapi 

`POST /deals` ([addADeal](https://github.com/pipedrive/client-php/blob/master/src/Controllers/DealsController.php#L189)) accepts the request body as an object, more about this endpoint [here](https://developers.pipedrive.com/docs/api/v1/#!/Deals/post_deals). If the request body is presented as an array it results in 400 error.
