### ISSUE TITLE
getAllDeals is not returning the custom fields

### ISSUE THREAD

**Issue by rubaiet** [pipedrive/client-php#51]
json mapper in getAllDeals is not returning the custom fields
`return CamelCaseHelper::keysToCamelCase($mapper->mapClass($response->body, 'Pipedrive\\Models\\GetDeals'));`

Better use this
`return CamelCaseHelper::keysToCamelCase($response->body);`

**Comment by ismaelrojas01** [comment]
Same with others DealsController's methods and other Controllers.
