### ISSUE TITLE
How to create a lead?

### ISSUE THREAD

**Issue by goear** [pipedrive/client-php#58]
I don't see any controller related to leads. Could you let me know which is the controller for create/delete leads?

**Comment by Aerendir** [comment]
It seems not implemented in the client.

The documentation has a tutorial about how to add a lead via API: https://pipedrive.readme.io/docs/adding-a-lead

But in the client library there is no trace of it...

**Comment by goear** [comment]
Yes, finally I implemented by myself patching it via curl. Thank you.

**Comment by Aerendir** [comment]
I think I will do the same...

**Comment by AlexL-JWA** [comment]
Cool in more than a year you couldn't make a controller to create a lead
