### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by caspahouzer** [pipedrive/client-php#6]
Missing variable
https://github.com/pipedrive/client-php/blob/master/src/Controllers/ActivitiesController.php#L229
https://github.com/pipedrive/client-php/blob/master/src/Controllers/ActivitiesController.php#L426

**Comment by caspahouzer** [comment]
There is a new version, but this issue isn't considered

**Comment by DenisButCheR** [comment]
Hello @caspahouzer . Thanks for your contribution. The bug is added to our backlog.

**Comment by mykhailo-riabokon** [comment]
@caspahouzer the issues were fixed in 1.1.1. Thank you for reporting.

**Comment by caspahouzer** [comment]
only one year 😄
