### ISSUE TITLE
Instead of hardcoded error message using actual messages would be incredible

### ISSUE THREAD

**Issue by Meeshalk** [pipedrive/client-php#68]
https://github.com/pipedrive/client-php/blob/f68f905b0c1671a70d14d7f7cf76234e68ad5d86/src/Controllers/BaseController.php#L66

**Comment by djoleeeee** [comment]
You can use: getResponseBody()

catch (\Pipedrive\APIException $e) {
    echo $e->getResponseBody());
}

**Comment by Meeshalk** [comment]
@djoleeeee this gives an hard coded error message. `HTTP Response Not OK`
Which is useless in many cases, specially in debugging.
