### ISSUE TITLE
"getDetailsOfADeal" doesn't contain Deal Custom Fields in response

### ISSUE THREAD

**Issue by takka** [pipedrive/client-php#70]
Hello!
I am trying to connect my project to PipeDrive and decided to use this php client, but I have some issues. 
 "getDetailsOfADeal" doesn't return custom fields, direct API call  response has them in "data", but when I use this client, $response ->data contains only default set of fields. 

Checked all the documentation I could, but still cannot find the answer, is there any way to get deal custom field value via this client?

**Comment by SpaceOven** [comment]
Hi!
What version of the SDK are you using?
I tried here with the latest one, it seems to be working. Here is my code snippet:
```
<?php

require_once __DIR__.'/../vendor/autoload.php';

session_start();

$apiToken = '<REPLACE WITH API TOKEN>';
$dealId = <REPLACE WITH DEAL ID>;

$client = new Pipedrive\Client(null, null, null, $apiToken); 

try {
    $body = [];
     echo '<div><h2>Get one deal with custom fields</h2><div>';
     $response = $client->getDeals()->getDetailsOfADeal($dealId);

     echo '<pre>';
     var_dump(json_encode($response->data, JSON_PRETTY_PRINT));
     echo '</pre>';

} catch (\Pipedrive\APIException $e) {
    echo $e;
}
```
It brings my custom field:
![image](https://user-images.githubusercontent.com/11083760/180205383-cb171d76-c428-4967-a88e-c83518f09c0d.png)
