### ISSUE TITLE
jsonSerialize method throughout the library is not consistent with JsonSerializable::jsonSerialize

### ISSUE THREAD

**Issue by stephen-ads** [pipedrive/client-php#78]
All `jsonSerialize` methods are without a return type, whereas interface signature `JsonSerializable::jsonSerialize` has return type `mixed`. This throws up warnings continually. One way or the other, they should be consistent with each other.

**Comment by youssef-saber-3** [comment]
@stephen-ads can you let us know if you're still facing this issue ?
