### ISSUE TITLE
StagesController:getAllStages does not work with no pipeline ID

### ISSUE THREAD

**Issue by alex-bukach** [pipedrive/client-php#8]
401 request is received.

**Comment by DenisButCheR** [comment]
Hello @alex-bukach. Thanks for your feedback. Looks like you right and currently pipelined is required param in our library. We will fix this in future versions of this library

**Comment by alex-bukach** [comment]
@DenisButCheR please check the attached pull request.

**Comment by alex-bukach** [comment]
This issue has been fixed in https://github.com/pipedrive/client-php/pull/9

**Comment by ziimk** [comment]
Thank you. This was fixed with the query builder modifications in #37 and #38 so an explicit check is no longer needed
