### ISSUE TITLE
Invalid Request Body Parameter Type

### ISSUE THREAD

**Issue by andres-forus** [pipedrive/client-php#87]
I try run a example: updateTheProductAttachedToADeal

### Request

`
$id = 27;
$collect['id'] = $id;

$productAttachmentId = 27;
$collect['productAttachmentId'] = $productAttachmentId;

$productId = 2;
$collect['productId'] = $productId;

$itemPrice = 27.9633801840075;
$collect['itemPrice'] = $itemPrice;

$quantity = 27;
$collect['quantity'] = $quantity;

$discountPercentage = 27.9633801840075;
$collect['discountPercentage'] = $discountPercentage;

$duration = 27.9633801840075;
$collect['duration'] = $duration;

$productVariationId = 27;
$collect['productVariationId'] = $productVariationId;

$comments = 'comments';
$collect['comments'] = $comments;

$enabledFlag = int::ENUM_0;
$collect['enabledFlag'] = $enabledFlag;

$result = $deals->updateTheProductAttachedToADeal($collect);
`

**Response**

`

  +body: {#1694
    +"success": false
    +"error": "body/product_id must be integer, body/item_price must be number, body/quantity must be number, body/discount_percentage must be number, body/product_variation_id must be integer, body/product_variation_id must be null, body/product_variation_id must match a schema in anyOf, body/duration must be number
`

**Comment by SpaceOven** [comment]
Hi! Thanks for bringing this to our attention. 🙂

We recently fixed a bug related to this function, it should be working normally on version 6.1.0

Cheers!
