### ISSUE TITLE
Configuration.php loading incompletely

### ISSUE THREAD

**Issue by abdulbakigul** [pipedrive/client-php#98]
i use this "composer require pipedrive/pipedrive"
command and my Configuration.php loading incompletely
for example i didnt acces setApiKey() function.
Am I making a mistake while uploading?
(my  Configuration.php row count 78 But there needs to be more rows)

**Comment by Reivilo85k** [comment]
Hi @abdulbakigul , sorry to have missed this one. It seems this issue was related to an older version, I assume the problem has been fixed. I will close the issue for now but feel free to reopen it if you need help.
